- src/models.cxx
If the plasticity model has no history data, the current code attempts to grab the address of a nonexistent entry in the history data array, which is fixed by this commit. 
ref #22
> Fix out of bounds error with no history

- src/cp/crystallography.cxx
- src/cp/crystallography.h
Their dbg runtime checks complain about const vectors at global scope.
> Fix for MOOSE integration

- doc/sphinx/damage/scalar.rst
- examples/damage.py
- verification/verify_classical_creep_strains.py
This adds a verification example showing that for negligible elasticity the Hayhurst-Leckie damage model implemented in NEML agrees exactly with the results in the paper for both strain and failure time.
It adds an explicit calculation of the damaged elastic slope to the "damage.py" example.
It clarifies in the documentation that the damage model rate form receives the effective stress (sigma/(1-omega)) and not the stress itself.
This is all connected to the difference between the "rate form" and "algebraic form" damage implementations that Aritra and I were working on.  For the record, NEML uses the "algebraic form", as described in the docs for the ScalarDamageModel class.
> Clarify and test creep damage definition

- src/neml_interface.h
- src/parse.cxx
- src/parse.h
- util/string_interface/cxxstring.cxx
This commit will allow the model name to be passed in along with the string containing the xml data.  This makes the string interface consistent with the xml interface.
> Allow model name to be used with xml string interface 

- src/history.h
This fix allows neml to be build in the standard Conda-based MOOSE macOS development environment (Clang 9.0.1 , `-std=c++14` option set).
```
cmake -DUSE_OPENMP=OFF . && make -j 8
```
(OpenMP configuration options are still not right on this platform so it needs to be disabled)
Closes #66
> Explicitly use int hash 

- .travis.yml
- CMakeLists.txt
- INSTALL.md
- README.md
- src/math/rotations.cxx
- src/objects.cxx
- src/objects.h
- test/drivers/test_drivers.sh
I don't like it, but it gets rid of boost and it fits within the design constraints of neml (namely the ability to build with and then link without python support). Ping @bwspenc (this is the low-brow approach)
> Use custom variant

- neml/arbbar.py
For some reason I left the solver tolerances for the arbbar model for the user inaccessible.  This fixes it...
> Pass through the tolerances for the arbbar solver

- src/cp/singlecrystal.cxx
- src/cp/singlecrystal.h
- src/creep.cxx
- src/creep.h
- src/damage.cxx
- src/damage.h
- src/larsonmiller.cxx
- src/larsonmiller.h
- src/models.cxx
- src/models.h
- src/solvers.cxx
- src/solvers.h
- src/solvers_wrap.cxx
- test/test_damage.py
- test/test_solvers.py
This adds a line search capability to the entire NEML nonlinear solver system.  It, however, only turns it on by default for the creep + plasticity models, in an effort to improve the robustness of the model integration.
> Creep integration

- CMakeLists.txt
- src/general_flow.cxx
- src/nemlerror.h
This branch provides a configuration compile-time limit `STRAIN_RATE_LIMIT` model developers can check strain rate values against (for example, in a stress rate calculation) to prevent conditions that would otherwise cause a `SIGFPE` with those compile-time options set.
> Added upper strain rate limit to NEML, applied to look at fixing issue #89

- .github/workflows/package.yml
- .github/workflows/test.yml
We just had a build failure that had nothing to do with the package.  It may have just been a random issue with the package repo, but maybe running update first will help in the future.
> Make apt a bit more stable in the build scripts

- .github/workflows/test.yml
The mac tests are failing because brew returns an error code if you includes a packages that is already installed in the `brew install` list.  Of course we don't know what a particular test instance will have installed so we need to cover this case.
> Brew treats upgrades as errors, need to ignore that

- src/parse.cxx
- src/parse.h
- test/malformed.xml
- test/test_parse.py
Currently we were segfaulting if the user asked for a model that did not exist in the XML file.  This PR fixes this issue and adds some extra testing to the parser to (hopefully) ensure it remains robust against errors like this.
> Updated parser to be more robust

- CMakeLists.txt
This change should force CMake to find python3 if both python3 and python2 are installed on a machine.
> Force NEML to find python3

- doc/sphinx/hardening/non/special_chaboche.rst
- doc/sphinx/hardening/nonassociative.rst
- include/hardening.h
- include/interpolate.h
- src/hardening.cxx
- src/hardening_wrap.cxx
- src/interpolate.cxx
- src/interpolate_wrap.cxx
- test/test_hardening.py
- test/test_interpolate.py
This PR adds a specialized variant of the Chaboche model which can be used "one-to-one" with parameters coming from pyoptmat fits.  The only changes versus our standard Chaboche kinematic + Voce isotropic hardening are:
1. Reparameterization of the Voce model
2. Static recovery on the Voce isotropic strength
3. Slight change in the definition of static recovery for the Chaboche kinematic backstress terms.
> Adds specialized Chaboche model compatible with pyoptmat

- examples/cp/cpmodel.xml
- examples/rate_independent.py
- include/math/rotations.h
- src/math/rotations.cxx
The CP classes now take a subclass of `Orientation` called `CrystalOrientation` as input, rather than `Orientation`.  This change required updating the XML files in the examples plus the `generate_random_orientations` routien.
> Fixes bug in new CrystalOrientation class

- include/cp/kinematics.h
- include/cp/singlecrystal.h
- src/cp/kinematics.cxx
- src/cp/singlecrystal.cxx
- src/cp/singlecrystal_wrap.cxx
- test/test_crystalmodels.py
This PR:
- Corrects the bug with elastic predictors in the crystal models
- Adds various switches to allow the user to apply an elastic predictor
> Creates various options for elastic predictors in the crystal model

- doc/sphinx/vp_flow.rst
- doc/sphinx/vp_flow/superimposed.rst
- include/visco_flow.h
- src/visco_flow.cxx
- src/visco_flow_wrap.cxx
- test/test_visco_flow.py
Add a viscoplastic flow rule that sums the contributions of multiple individual flow rules.
Scalar flow rates are summed, flow directions are weighted by the flow rates and summed, and the sets of internal variables are combined together.
> Add composite flow rule

- doc/sphinx/damage/work.rst
- include/damage.h
- src/damage.cxx
- test/test_damage.py
Allows log interpolation for the critical work to failure.
> Work damage update

- doc/sphinx/cp/crystallography/GeneralLattice.rst
- doc/sphinx/cp/crystallography/Lattice.rst
- include/cp/crystallography.h
- src/cp/crystallography.cxx
- src/cp/crystallography_wrap.cxx
- test/test_crystallography.py
Add a class that lets the user specify an arbitrary lattice geometry by giving the three lattice vectors + the symmetry group.
> Add a general lattice class

- .github/workflows/test.yml
Looks like brew install now picks python 3.11 on Mac.  I need to update the build script to match.
> Increment mac build python version to 3.11

- src/damage.cxx
Adds `stdexecpt` which some stack overflow randomness suggests is required...
> Potential compiler fix for weird limits error

- .clang-format
- .gitignore
- examples/cp/generalizedhucocks/generate_model.py
- examples/cp/generalizedhucocks/just-aging.py
- examples/cp/generalizedhucocks/model.xml
- examples/cp/hucocks/generate_model.py
- include/cp/generalizedhucocks.h
- include/parse.h
- src/cp/CMakeLists.txt
- src/cp/generalizedhucocks.cxx
- src/cp/generalizedhucocks_wrap.cxx
- src/cp/hucocks.cxx
- src/parse.cxx
- test/test_generalizedhucocks.py
I am prepending the class names with `Generalized`... 
In principle this should be a drop-in replacement to the original Hu-Cocks model where all precipitates are decoupled. So let's decide whether to keep the old version. If not, I'll do the conversion.
> Generalized HuCocks model

- CMakeLists.txt
- examples/cp/hucocks/model.xml
- profiling/models.txt
- profiling/reference.xml
- src/history.cxx
As it says, now setting `PRODUCTION_BUILD` to true in CMake will disable some error checking that was significantly slowing down the generalized hu cocks model.  On my  machine it goes from about 8 s in a test to 4.5 s.
This also adds both variants of the model to the profiling checks.
> Added an option to disable expensive error checking on production runs

- include/neml_interface.h
Turns out deer uses `Vector` and `Orientation` from the NEML API and we didn't include those in the public interface.  Linkers are getting too clever for their own good and not including the symbol.
> Add tensors to the interface

- .github/workflows/package.yml
- .github/workflows/test_packages.yml
- README.md
- doc/sphinx/conf.py
- setup.py
Add prebuilt python 3.11 binaries.
> Add python 3.11, update version
