verification/verify_yield.py
Closes #3 , tests process of merging.
=> Test pull request

ACKNOWLEDGEMENTS.md
Pointless test to show how this works.
=> Made pointless change to close issue #5

doc/sphinx/creep/s_generic.rst, doc/sphinx/creep/scalar.rst, src/creep.cxx, src/creep.h, src/creep_wrap.cxx, test/test_creep.py
Implemented a generic creep rate function where the creep rate is given as a generic function of log stress, implemented using the interpolation objects.
Closes #8
=> Generic creep interpolation

src/parse.cxx, src/parse.h
=> Fix constness for get_child 

src/creep.cxx, src/damage.cxx, src/elasticity.cxx, src/general_flow.cxx, src/hardening.cxx, src/interpolate.cxx, src/models.cxx, src/parse.cxx, src/ri_flow.cxx, src/surfaces.cxx, src/visco_flow.cxx
=> Disambiguate calls to neml::make_unique

doc/sphinx/damage/effective/effective.rst, doc/sphinx/damage/effective/huddleston.rst, doc/sphinx/damage/effective/maxprincipal.rst, doc/sphinx/damage/effective/maxseveral.rst, doc/sphinx/damage/effective/vonmises.rst, doc/sphinx/damage/modular.rst, doc/sphinx/damage/scalar.rst, doc/sphinx/hardening/simple.rst, doc/sphinx/references.rst, src/damage.cxx, src/damage.h, src/damage_wrap.cxx, src/nemlmath.cxx, src/nemlmath.h, src/nemlmath_wrap.cxx, src/objects.cxx, src/objects.h, test/test_damage.py, test/test_nemlmath.py
Adds a modular classical creep damage system for trying out different effective stresses.  Also provides an option for creep damage that is fully consistent with the classical Hayhurst-Leckie anayltical solutions.
=> Multidamage

doc/sphinx/damage.rst, doc/sphinx/damage/effective/effective.rst, doc/sphinx/damage/effective/sumseveral.rst, src/damage.cxx, src/damage.h, src/damage_wrap.cxx, test/test_damage.py
This implements an effective stress that is defined by a sum of other effective stress measures.
=> Sum several effective stresses

doc/sphinx/creep/s_blackburn.rst, doc/sphinx/creep/s_swindeman.rst, doc/sphinx/creep/scalar.rst, doc/sphinx/references.rst, src/creep.cxx, src/creep.h, src/creep_wrap.cxx, test/test_creep.py
Added new minimum creep rate models from Swindeman and Blackburn.
=> New minimum creep rate models

doc/sphinx/hardening/simple/iso_power.rst, doc/sphinx/hardening/simple/isotropic.rst, examples/example.xml, examples/power-law.py, src/hardening.cxx, src/hardening.h, src/hardening_wrap.cxx, test/test_hardening.py
Added simple power law hardening (flow = sigma_0 + K * eps_p ** n) for Bipul.
=> Added power law hardening for Bipul

examples/cp/compare_misorientation.py, examples/cp/misorientation.py, src/cp/crystallography.cxx, src/cp/crystallography.h, src/cp/crystallography_wrap.cxx, src/cp/singlecrystal.cxx, src/cp/singlecrystal.h, src/cp/singlecrystal_wrap.cxx, src/math/nemlmath.cxx, src/math/nemlmath.h, src/math/nemlmath_wrap.cxx, src/math/rotations.cxx, src/math/rotations.h, src/math/rotations_wrap.cxx, test/test_crystallography.py, test/test_crystalmodels.py, test/test_nemlmath.py, test/test_rotations.py
Revise NEML to handle a few issues in the crystal models:
1. Faster misorientation calculation
2. singlecrystal strength takes a raw history vector
3. Actually call the angle conversion, if requested, in rotations get_axis_angle
=> Faster misorientation

doc/sphinx/creep/s_crmo.rst, doc/sphinx/creep/s_km.rst, doc/sphinx/creep/s_normpower.rst, doc/sphinx/creep/scalar.rst, doc/sphinx/interpolate.rst, src/creep.cxx, src/creep.h, src/creep_wrap.cxx, src/parse.cxx, test/test_creep.py
Adds all the accoutrements needed to implement the minimum creep rate models in the new draft of the EPP primary load code case.
=> Creep rules

doc/sphinx/damage/effective/effective.rst, doc/sphinx/damage/effective/meanstress.rst, src/damage.cxx, src/damage.h, src/damage_wrap.cxx
This PR adds the `MeanEffectiveStress` and fix a bug in `HudllestonEffectiveStress` preventing some calculation to run. 
close #48
=> added mean effective stress and fixed huddleston

src/larsonmiller.cxx
=> Attempted fix for Will's problem

.gitignore, CMakeLists.txt, MANIFEST.in, README.md, setup.cfg, setup.py, src/CMakeLists.txt, src/cp/CMakeLists.txt, src/math/CMakeLists.txt
Simple changes to provide a python source package for PyPi.
=> Added ability to build a python source package

examples/axi.py, neml/arbbar.py, neml/axisym.py
Apparently networkx updated their API.  Specifically node -> nodes. Arg.
=> Fix arbbar models for new networkx API

.travis.yml, test/drivers/test_drivers.sh
Testbed for adding:
- C/CXX/fortran driver tests
- Configuration with and without pybind
- GCC version testing
- Platform testing?
to the travis-ci test setup.
=> Added simple test of drivers with pybind compiled

.github/workflows/test.yml, README.md
=> Test both release and debug builds

.github/workflows/test.yml, doc/sphinx/install/mac.rst, doc/sphinx/started.rst, src/objects.h, src/parse.h
This PR adds macos testing comparable to the existing linux test suite.
=> Include macos testing

.github/workflows/package.yml, MANIFEST.in, doc/sphinx/conf.py, doc/sphinx/started.rst, setup.py
Updates pypi automatically with new release.
=> Added automatic packing to PyPi with new release

doc/sphinx/vp_flow/chaboche.rst, src/visco_flow.cxx, src/visco_flow.h, test/test_visco_flow.py
This PR adds a prefactor to the Chaboche flow rule
closes #93
=> add prefactor to chaboche

profiling/check_memory.sh, profiling/models.txt, profiling/profile_single.sh, profiling/reference.xml, profiling/run_single.sh, profiling/time_all.sh
The new regression test system broke how I was running the timing/memory use profiles.
=> Fix profiling system to reflect new regression tests

.github/workflows/test.yml, .gitignore, CMakeLists.txt, doc/sphinx/conf.py, doc/sphinx/install/linux.rst, doc/sphinx/install/windows.rst, neml/__init__.py, src/CMakeLists.txt, src/block.h, src/cinterface.h, src/cp/crystaldamage.h, src/math/nemlmath.h, src/math/projections.h, src/objects.cxx, src/objects.h, src/parse.h, src/solvers.h, src/walker.h, src/windows.h, test/drivers/test_drivers.sh
Users apparently want better Windows support 😦.  But I'll give it an attempt.
This PR will add basic _automatic_ windows support, including testing.
=> Make neml compile on windows

doc/sphinx/vp_flow.rst, doc/sphinx/vp_flow/linear.rst, include/visco_flow.h, src/visco_flow.cxx, src/visco_flow_wrap.cxx, test/test_visco_flow.py
=> Added a simple linear viscous flow rule

.github/workflows/package.yml, .github/workflows/test.yml, .github/workflows/test_packages.yml
=> Updated mac bindings to use python3.10

include/cp/batch.h, include/cp/polycrystal.h, neml/cp/polefigures.py, src/cp/batch.cxx, src/cp/polycrystal.cxx, src/cp/polycrystal_wrap.cxx
Just modifies the IPF plotting routine so you can visualize reiorientation.
=> Added simple trajectory plotting routine for IPF reorientation

.github/workflows/test.yml, profiling/models.txt, profiling/reference.xml, src/models.cxx
Hopefully fixed our memory issues.  Added valgrind to regular testing.
=> Fixed leak in creep + plasticity

doc/requirements.txt, doc/sphinx/conf.py
Updates documentation year and theme.  Should fix html as well, hopefully.
=> Documentation update

doc/sphinx/conf.py
Trying to fix the issue rendering the equations using imgmath on rtd.
=> Fix imgmath

CMakeLists.txt, doc/sphinx/conf.py, setup.py
=> Update package build
